##Get all users
GET http://localhost:5001/api/users HTTP/1.1

### getall
GET http://localhost:5001/api/users/c0517452-b6da-49d3-85b3-e157c5d3bdd9/games



### test endpoint
GET http://localhost:5001/api/games



### both are get user games.
GET http://localhost:5000/api/users/82dbe0ec-770f-4be0-ae9f-e8727f81c00d/games

### cerate user. temporary in this service.

POST http://localhost:5000/api/users HTTP/1.1
content-type: application/json

{
    "username": "testowy_user2",
    "password": "mocnehaslo",
    "email": "test@email.com"
}

### create new game (address can be added)

POST http://localhost:5001/api/games HTTP/1.1
content-type: application/json

{
    "name": "new-game2",
    "gameDate": "2019-07-28",
    "ownerId": "c0517452-b6da-49d3-85b3-e157c5d3bdd9"
}

###

PUT http://localhost:5000/api/games/d5c93501-c17c-4ab7-1193-08d7915961c5/attendees HTTP/1.1
content-type: application/json

{
    "newAttendeeId": "82dbe0ec-770f-4be0-ae9f-e8727f81c00d"
}
###
# get game
GET http://localhost:5000/api/games/d5c93501-c17c-4ab7-1193-08d7915961c5

###
#update place
PUT http://localhost:5000/api/games/d5c93501-c17c-4ab7-1193-08d7915961c5/places HTTP/1.1
content-type: application/json

{
    "street": "tyniecka",
    "number": 39
}

###
#set availability 
PUT http://localhost:5000/api/games/d5c93501-c17c-4ab7-1193-08d7915961c5/attendees/available HTTP/1.1
content-type: application/json

{
    "userId": "82dbe0ec-770f-4be0-ae9f-e8727f81c00d",
    "isAvailable": true
}