GET https://futbalmng.serveo.net:6010/api/users/5ebbf591-f261-4a7c-ab76-82e4d5cfebe0/mygames

### both are get user games.

GET https://localhost:6010/api/users/5ebbf591-f261-4a7c-ab76-82e4d5cfebe0/mygames

### cerate user. temporary in this service.

POST https://localhost:6010/api/users HTTP/1.1
content-type: application/json

{
    "userName": "testowy_user2",
    "password": "mocnehaslo",
    "email": "test@email.com"
}

### create new game (address can be added)

POST https://localhost:6010/api/games HTTP/1.1
content-type: application/json

{
    "name": "new-game2",
    "gameDate": "2019-07-28",
    "ownerId": "5ebbf591-f261-4a7c-ab76-82e4d5cfebe0"
}

###

PUT https://localhost:6010/api/games/e6ac5143-d58b-48a8-26e5-08d711fc5926/attendees/266cad8a-c1f0-428a-9801-84ce5ed7ab2a HTTP/1.1
content-type: application/json

###
GET https://localhost:6010/api/games/e6ac5143-d58b-48a8-26e5-08d711fc5926

###
#update place
PUT https://localhost:6010/api/games/6d1e237d-d9ed-4b46-39d5-08d75edf11a9/places HTTP/1.1
content-type: application/json

{
    "street": "tyniecka",
    "number": 39
}
