production:
  production_environment: true
  required_contexts: ["build"]
  environment: development
  description: 'development'
  payload:
    value_files: ["./config/production.yml", "./config/_common.yml"]
    # Remove the canary deployment if it exists when doing a full prod deploy.
    remove_canary: true
    release: futchart
    namespace: default
    track: stable
    values:
      replicaCount: 1