version: "3"
services:
    web:
      build: .
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
      ports:
      # Replace the values on the left by the values on your launchSettings.json
        - "5000:5000"
        - "6010:443"
        # depends_on:
        #     - db
    # db:
    #     image: "mcr.microsoft.com/mssql/server"
    #     environment:
    #         SA_PASSWORD: "Your_password123"
    #         ACCEPT_EULA: "Y"