version: "3"
services:
    web:
      build: .
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=https://localhost;http://localhost
        - ASPNETCORE_HTTPS_PORT=44349  
      ports:
      # Replace the values on the left by the values on your launchSettings.json
        - "5000:80"
        - "6010:443"
      volumes:
        - ${HOME}/Microsoft/UserSecrets/:/root/.microsoft/usersecrets
        - ${HOME}/ASP.NET/Https:/root/.aspnet/https/
        # depends_on:
        #     - db
    # db:
    #     image: "mcr.microsoft.com/mssql/server"
    #     environment:
    #         SA_PASSWORD: "Your_password123"
    #         ACCEPT_EULA: "Y"