version: '3.5'

services:
  futbalmngapi:
    container_name: futbalmngapi
    image: futbalmng/dokeapi
    build:
      context: .
      dockerfile: Dockerfile.debug
    ports:
      - 5001:5001
    networks:
      - futbalmng
    volumes:
      - './:/app'
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - futbalmng

    # network_mode: host
    volumes: 
      - rabbitmq:/var/lib/rabbitmq

networks:
  futbalmng:
    name: futbal-network

volumes:
  rabbitmq:
    driver: local