{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "futchart.serviceAccountName" . }}
  labels:
{{ include "futchart.labels" . | nindent 4 }}
{{- end -}}
