# .github/deploy.yml
name: Deploy
on: ['deployment']

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v1
    - name: 'Deploy'
      uses: 'deliverybot/helm3@v1'
      with:
        namespace: 'default'
        secrets: '${{ toJSON(secrets) }}'
        chart: 'futchart'
        token: '${{ github.token }}'
        release: futbalapi
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'