name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      with: # Set the secret as an input
        cr_pass: ${{ secrets.CONTAINER_PWD }}
        cr_usr: ${{ secrets.CONTAINER_USR }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: dotnet test
      run: docker login ${{ with.cr_usr }}/azureacr.io -p {{ with.cr_pass }}
      run: docker build . -t tomzreacr.azurecr.io/futbalapi
      run: docker push tomzreacr.azurecr.io/futbalapi